# Generated by Django 3.0.9 on 2024-12-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotModel',
            fields=[
                ('model', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Модель робота')),
            ],
            options={
                'verbose_name': 'Модель робота',
                'verbose_name_plural': 'Модели роботов',
            },
        ),
        migrations.CreateModel(
            name='RobotSerial',
            fields=[
                ('serial', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Серия робота')),
            ],
            options={
                'verbose_name': 'Серия робота',
                'verbose_name_plural': 'Серии роботов',
            },
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=2, verbose_name='Версия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество роботов в наличии')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotModel', verbose_name='Модель')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robots.RobotSerial', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Робот',
                'verbose_name_plural': 'Роботы',
                'ordering': ('-created_at',),
                'unique_together': {('serial_id', 'model_id')},
            },
        ),
    ]
